QT.winextras_private.VERSION = 5.2.1
QT.winextras_private.MAJOR_VERSION = 5
QT.winextras_private.MINOR_VERSION = 2
QT.winextras_private.PATCH_VERSION = 1
QT.winextras_private.name = QtWinExtras
QT.winextras_private.libs = $$QT_MODULE_LIB_BASE
QT.winextras_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWinExtras/5.2.1 $$QT_MODULE_INCLUDE_BASE/QtWinExtras/5.2.1/QtWinExtras
QT.winextras_private.depends = winextras
QT.winextras_private.module_config = staticlib internal_module no_link
